/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#1a1a1a",
        "primary-fixed": "#ffcc00",
        "primary-fixed-dim": "#e6b800",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#1a1a1a",
        "on-primary-container": "#1a1a1a",
        "primary-container": "#ffcc00",
        secondary: "#e63b2e",
        "on-secondary": "#1a1a1a",
        "on-secondary-fixed": "#1a1a1a",
        "on-secondary-container": "#1a1a1a",
        "secondary-fixed": "#ffdad6",
        "secondary-fixed-dim": "#ffb3ab",
        "secondary-container": "#ffdad6",
        tertiary: "#0055ff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#d6e3ff",
        "tertiary-fixed-dim": "#a8c6ff",
        "tertiary-container": "#d6e3ff",
        "on-tertiary-container": "#1a1a1a",
        background: "#f5f0e8",
        "on-background": "#1a1a1a",
        surface: "#f5f0e8",
        "on-surface": "#1a1a1a",
        "surface-variant": "#e8e3da",
        "on-surface-variant": "#4a4a4a",
        "surface-container": "#eee9e0",
        "surface-container-low": "#f2ede5",
        "surface-container-high": "#e8e3da",
        "surface-container-highest": "#e2ddd4",
        "surface-container-lowest": "#ffffff",
        outline: "#1a1a1a",
        "outline-variant": "#d0cbc3",
        error: "#cc0000",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px",
      },
    },
  },
  plugins: [],
};
